proxy:
  image: edmilsonsantana/proxy:1.0
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=localhost
    - NGINX_PROXY=http://identidock:9090

identidock:
  image: edmilsonsantana/identidock:newest
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD

dnmonster:
  image: amouat/dnmonster

redis:
  image: redis

logspout:
  image: amouat/logspout-logstash
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:80"
  command: logstash+tcp://consultoriasantana.com.br:5000
