proxy:
  image: edmilsonsantana/proxy:1.0
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=localhost
    - NGINX_PROXY=http://identidock:9090

identidock:
  image: edmilsonsantana/identidock:newest
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD

dnmonster:
  image: amouat/dnmonster

redis:
  image: redis

logstash:
  image: logstash:5
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  environment:
    LOGSTASH: ignore
  command: -w -f /etc/logstash.conf

logspout:
  image: amouat/logspout-logstash
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:80"
  links:
    - logstash
  command: logstash://logstash:5000
